version: '3.5'

services:
  web:
    image: digitpeak/dpdocker-web:${PHP_VERSION}
    environment:
      STARTUP_COMMAND_1: cp /var/www/html/Projects/DPDocker/webserverc/scripts/index.php /var/www/html
      STARTUP_COMMAND_2: php /var/www/html/Projects/DPDocker/webserverc/scripts/setup-joomla-site.php ${JOOMLA_FOLDER} ${EXTENSION} ${DB} ${JOOMLA_VERSION} ${REBUILD} ${EXTENSIONBASEDIR}
      STARTUP_COMMAND_3: /var/www/html/Projects/DPDocker/webserverc/scripts/install-joomla.sh ${JOOMLA_FOLDER} ${DB} ${JOOMLA_VERSION} ${REBUILD}
    links:
      - mysql:mysql
      - mailcatcher:mailcatcher
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ./zips:/zips
      - ../..:/var/www/html/Projects
      - ../..:/usr/src/Projects
      - ${EXTENSIONBASEDIR}:${EXTENSIONBASEDIR}

  mysql:
    image: mysql:${MYSQL_DBVERSION}
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./mysql_${MYSQL_DBVERSION}_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql
    ports:
      - 81:80

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 83:1080
