version: '3.5'

services:
  system-testsc:
    image: digitpeak/dpdocker-cli:7.4
    command: /usr/src/Projects/DPDocker/testsc/scripts/exec-system-tests.sh ${EXTENSION} ${JOOMLA_VERSION} ${BROWSER} ${TEST}
    links:
      - mailcatcher-test
    volumes:
      - ../..:/usr/src/Projects
      - /tmp/testsc:/tmp/testsc

  selenium-test:
    image: selenium/standalone-${BROWSER}${DEBUG}:3.141.59-20210128
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/testsc:/tmp/testsc
      - ../..:/usr/src/Projects

  web-test:
    image: digitpeak/dpdocker-web:${PHP_VERSION}
    environment:
      STARTUP_COMMAND_1: php /var/www/html/Projects/DPDocker/webserverc/scripts/setup-joomla-site.php ${JOOMLA_FOLDER} ${EXTENSION} ${DB} ${JOOMLA_VERSION} ${REBUILD} ${EXTENSIONBASEDIR}
    links:
      - mysql-test
      - mailcatcher-test
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
      - ../..:/var/www/html/Projects
      - ../..:/usr/src/Projects

  mysql-test:
    image: mysql:${MYSQL_DBVERSION}
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin-test:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-test
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql-test
    ports:
      - 8081:80

  mailcatcher-test:
    image: schickling/mailcatcher
    ports:
      - 8082:1080
