version: '3.5'

services:
  build:
    image: digitpeak/dpdocker-cli
    command: 
      sh -c "/usr/src/Projects/DPDocker/buildc/scripts/exec-build.sh ${EXTENSION} ${VERSION} ${EXTENSIONBASEDIR} ${SRCFOLDER} ${BUILDACTIVE}"
    volumes:
      - ../..:/usr/src/Projects
      - ${BASEDIR}:${BASEDIR}
